version: '3'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - API_PORT=8081
    ports:
      - "8081:8081"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  pyroscope:
    container_name: pyroscope
    image: pyroscope/pyroscope:latest
    command: server
    ports:
      - "4040:4040"
    volumes:
      - ./pyroscope.yml:/etc/pyroscope/server.yml