// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/metrics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricsAggregator_StreamMetrics_FullMethodName = "/metrics.MetricsAggregator/StreamMetrics"
	MetricsAggregator_SetThreshold_FullMethodName  = "/metrics.MetricsAggregator/SetThreshold"
	MetricsAggregator_HealthCheck_FullMethodName   = "/metrics.MetricsAggregator/HealthCheck"
	MetricsAggregator_JoinCluster_FullMethodName   = "/metrics.MetricsAggregator/JoinCluster"
)

// MetricsAggregatorClient is the client API for MetricsAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsAggregatorClient interface {
	// Bidirectional streaming: client pushes metrics, server streams back alerts + aggregates.
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MetricsAggregator_StreamMetricsClient, error)
	// Set alert thresholds dynamically.
	SetThreshold(ctx context.Context, in *SetThresholdRequest, opts ...grpc.CallOption) (*SetThresholdResponse, error)
	// Health check.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Join a node to the Raft cluster.
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
}

type metricsAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsAggregatorClient(cc grpc.ClientConnInterface) MetricsAggregatorClient {
	return &metricsAggregatorClient{cc}
}

func (c *metricsAggregatorClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MetricsAggregator_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MetricsAggregator_ServiceDesc.Streams[0], MetricsAggregator_StreamMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &metricsAggregatorStreamMetricsClient{stream}
	return x, nil
}

type MetricsAggregator_StreamMetricsClient interface {
	Send(*Metric) error
	Recv() (*AggregatedMetric, error)
	grpc.ClientStream
}

type metricsAggregatorStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *metricsAggregatorStreamMetricsClient) Send(m *Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricsAggregatorStreamMetricsClient) Recv() (*AggregatedMetric, error) {
	m := new(AggregatedMetric)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metricsAggregatorClient) SetThreshold(ctx context.Context, in *SetThresholdRequest, opts ...grpc.CallOption) (*SetThresholdResponse, error) {
	out := new(SetThresholdResponse)
	err := c.cc.Invoke(ctx, MetricsAggregator_SetThreshold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsAggregatorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MetricsAggregator_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsAggregatorClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, MetricsAggregator_JoinCluster_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsAggregatorServer is the server API for MetricsAggregator service.
// All implementations must embed UnimplementedMetricsAggregatorServer
// for forward compatibility
type MetricsAggregatorServer interface {
	// Bidirectional streaming: client pushes metrics, server streams back alerts + aggregates.
	StreamMetrics(MetricsAggregator_StreamMetricsServer) error
	// Set alert thresholds dynamically.
	SetThreshold(context.Context, *SetThresholdRequest) (*SetThresholdResponse, error)
	// Health check.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Join a node to the Raft cluster.
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
	mustEmbedUnimplementedMetricsAggregatorServer()
}

// UnimplementedMetricsAggregatorServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsAggregatorServer struct {
}

func (UnimplementedMetricsAggregatorServer) StreamMetrics(MetricsAggregator_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedMetricsAggregatorServer) SetThreshold(context.Context, *SetThresholdRequest) (*SetThresholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetThreshold not implemented")
}
func (UnimplementedMetricsAggregatorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMetricsAggregatorServer) JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedMetricsAggregatorServer) mustEmbedUnimplementedMetricsAggregatorServer() {}

// UnsafeMetricsAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsAggregatorServer will
// result in compilation errors.
type UnsafeMetricsAggregatorServer interface {
	mustEmbedUnimplementedMetricsAggregatorServer()
}

func RegisterMetricsAggregatorServer(s grpc.ServiceRegistrar, srv MetricsAggregatorServer) {
	s.RegisterService(&MetricsAggregator_ServiceDesc, srv)
}

func _MetricsAggregator_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsAggregatorServer).StreamMetrics(&metricsAggregatorStreamMetricsServer{stream})
}

type MetricsAggregator_StreamMetricsServer interface {
	Send(*AggregatedMetric) error
	Recv() (*Metric, error)
	grpc.ServerStream
}

type metricsAggregatorStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *metricsAggregatorStreamMetricsServer) Send(m *AggregatedMetric) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricsAggregatorStreamMetricsServer) Recv() (*Metric, error) {
	m := new(Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MetricsAggregator_SetThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAggregatorServer).SetThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsAggregator_SetThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAggregatorServer).SetThreshold(ctx, req.(*SetThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsAggregator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAggregatorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsAggregator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAggregatorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsAggregator_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsAggregatorServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsAggregator_JoinCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsAggregatorServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsAggregator_ServiceDesc is the grpc.ServiceDesc for MetricsAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsAggregator",
	HandlerType: (*MetricsAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetThreshold",
			Handler:    _MetricsAggregator_SetThreshold_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MetricsAggregator_HealthCheck_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _MetricsAggregator_JoinCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MetricsAggregator_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/metrics.proto",
}
